/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as BuyerNegotiateRouteImport } from './routes/buyer/negotiate'
import { Route as BuyerDashboardRouteImport } from './routes/buyer/dashboard'
import { Route as BuyerCropsRouteImport } from './routes/buyer/crops'
import { Route as BuyerBidRouteImport } from './routes/buyer/bid'
import { Route as PublicDashboardRouteImport } from './routes/_public/dashboard'
import { Route as PublicAboutRouteImport } from './routes/_public/about'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const BuyerNegotiateRoute = BuyerNegotiateRouteImport.update({
  id: '/buyer/negotiate',
  path: '/buyer/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerCropsRoute = BuyerCropsRouteImport.update({
  id: '/buyer/crops',
  path: '/buyer/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerBidRoute = BuyerBidRouteImport.update({
  id: '/buyer/bid',
  path: '/buyer/bid',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDashboardRoute = PublicDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/dashboard': typeof PublicDashboardRoute
  '/buyer/bid': typeof BuyerBidRoute
  '/buyer/crops': typeof BuyerCropsRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/negotiate': typeof BuyerNegotiateRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/dashboard': typeof PublicDashboardRoute
  '/buyer/bid': typeof BuyerBidRoute
  '/buyer/crops': typeof BuyerCropsRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/negotiate': typeof BuyerNegotiateRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/dashboard': typeof PublicDashboardRoute
  '/buyer/bid': typeof BuyerBidRoute
  '/buyer/crops': typeof BuyerCropsRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/negotiate': typeof BuyerNegotiateRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/buyer/bid'
    | '/buyer/crops'
    | '/buyer/dashboard'
    | '/buyer/negotiate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/buyer/bid'
    | '/buyer/crops'
    | '/buyer/dashboard'
    | '/buyer/negotiate'
    | '/'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/dashboard'
    | '/buyer/bid'
    | '/buyer/crops'
    | '/buyer/dashboard'
    | '/buyer/negotiate'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  BuyerBidRoute: typeof BuyerBidRoute
  BuyerCropsRoute: typeof BuyerCropsRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  BuyerNegotiateRoute: typeof BuyerNegotiateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/buyer/negotiate': {
      id: '/buyer/negotiate'
      path: '/buyer/negotiate'
      fullPath: '/buyer/negotiate'
      preLoaderRoute: typeof BuyerNegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/crops': {
      id: '/buyer/crops'
      path: '/buyer/crops'
      fullPath: '/buyer/crops'
      preLoaderRoute: typeof BuyerCropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/bid': {
      id: '/buyer/bid'
      path: '/buyer/bid'
      fullPath: '/buyer/bid'
      preLoaderRoute: typeof BuyerBidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/dashboard': {
      id: '/_public/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicDashboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicDashboardRoute: typeof PublicDashboardRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicDashboardRoute: PublicDashboardRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  BuyerBidRoute: BuyerBidRoute,
  BuyerCropsRoute: BuyerCropsRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  BuyerNegotiateRoute: BuyerNegotiateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
